### ISSUE TITLE
구현 방식 협의(package or cli)

### ISSUE THREAD

**Issue by seungdeok** [team-moeum/moeum-eslint-prettier-toolkit#7]
## 💡 기능 설명
- package 방식과 CLI중 어떤 방식으로 구현할지 협의합니다.

## 🔍 주요 변경 사항
- N/A

## 🔗 참고 자료
- package 방식: `@moeum/eslint-config-base`
- CLI 방식: `npx create-moeum-config {project}`
- 묶어서 CLI로 생성하는데 package로 패키징도 하는 방법

**Comment by seungdeok** [comment]
@widse 
CLI로 prettier와 prettier & eslint ignore까지 초기세팅할 수 있을 것 같다는 생각이 들었습니다.

**Comment by widse** [comment]
CLI + Pacakge 둘다 구현 하기로 결정.
